# Generated by Django 5.0 on 2024-04-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0002_multimediaprincipal_multimediasecundaria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediaprincipal',
            name='imagen_principal',
            field=models.ImageField(upload_to='static/img/multimedia_principal/'),
        ),
        migrations.AlterField(
            model_name='multimediasecundaria',
            name='archivo',
            field=models.FileField(upload_to='static/.mp4/'),
        ),
    ]
