# Generated by Django 5.0 on 2024-04-18 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0003_alter_multimediaprincipal_imagen_principal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='multimediasecundaria',
            name='archivo',
            field=models.FileField(upload_to='static/img/multimedia_secundaria/'),
        ),
    ]
