# Generated by Django 5.0.4 on 2024-04-18 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0004_alter_multimediasecundaria_archivo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MultimediaPrincipal',
        ),
        migrations.DeleteModel(
            name='MultimediaSecundaria',
        ),
    ]
