# Generated by Django 5.0.4 on 2024-04-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0006_rifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rifa',
            name='descripcion',
            field=models.CharField(max_length=500),
        ),
    ]
