# Generated by Django 5.0.4 on 2024-04-19 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0007_alter_rifa_descripcion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenesRifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='img_principal')),
            ],
        ),
    ]
