# Generated by Django 5.0.4 on 2024-04-19 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0008_imagenesrifa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagenesrifa',
            name='imagen',
            field=models.ImageField(upload_to='static/img/imgPrincipal'),
        ),
    ]
