# Generated by Django 5.0.4 on 2024-04-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0009_alter_imagenesrifa_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagenP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='static/img/imgPrincipal')),
            ],
        ),
        migrations.AlterField(
            model_name='imagenesrifa',
            name='imagen',
            field=models.ImageField(upload_to='static/img/imagscroll'),
        ),
    ]
