# Generated by Django 5.0.4 on 2024-04-21 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0010_imagenp_alter_imagenesrifa_imagen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenesrifa',
            old_name='imagen',
            new_name='imagenes',
        ),
    ]
