# Generated by Django 5.0.4 on 2024-04-21 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0011_rename_imagen_imagenesrifa_imagenes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagenesrifa',
            old_name='imagenes',
            new_name='imagen',
        ),
    ]
