# Generated by Django 5.0.4 on 2024-04-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0013_imagen_delete_imagenesrifa_delete_imagenp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagen',
            name='imagen',
            field=models.ImageField(upload_to='static/img/imagenes'),
        ),
    ]
