# Generated by Django 5.0.4 on 2024-04-21 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0014_alter_imagen_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='rifa',
            name='rango_numeros',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='rifa',
            name='valor_por_numero',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
