# Generated by Django 5.0.4 on 2024-04-24 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0017_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SorteoAnterior',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_ganador', models.IntegerField(unique=True)),
                ('fecha_sorteo', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
