# Generated by Django 5.0.4 on 2024-04-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0018_sorteoanterior'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteoanterior',
            name='numero_ganador',
            field=models.IntegerField(),
        ),
    ]
