<<<<<<< HEAD
# Generated by Django 5.0.4 on 2024-04-25 04:12
=======
# Generated by Django 5.0.4 on 2024-04-25 02:55
>>>>>>> b0ce64ea1e7467674ee83ea56b349d277be1eb28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0019_alter_sorteoanterior_numero_ganador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteoanterior',
            name='numero_ganador',
<<<<<<< HEAD
            field=models.IntegerField(max_length=5),
=======
            field=models.IntegerField(),
>>>>>>> b0ce64ea1e7467674ee83ea56b349d277be1eb28
        ),
    ]
