# Generated by Django 5.0.4 on 2024-04-25 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0019_alter_sorteoanterior_numero_ganador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sorteoanterior',
            name='numero_ganador',
            field=models.IntegerField(max_length=5),
        ),
    ]
