# Generated by Django 5.0.4 on 2024-04-25 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RifaApp', '0020_alter_sorteoanterior_numero_ganador'),
    ]

    operations = [
        migrations.DeleteModel(
            name='logo',
        ),
    ]
